# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # - run: |
          # ls
      
      - name: Liquibase Github Action
      # You may pin to the exact commit or the version.
        uses: liquibase/liquibase-github-action@v2
        with:
            # Operation to run
            operation: 'update'
            # Path to Change Log directory
            classpath: '/'
            # Name of Change Log File
            changeLogFile: 'main_changelog.xml'
            # Database Username
            username: ${{ secrets.USERNAME }}
            # Database Password
            password: ${{ secrets.PASSWORD }}
            # Database URL
            url: ${{ secrets.URL }}
            # Count for updateCount and rollbackCount
            #count: # optional
            # Tag for tag, updateToTag, and rollback
            #tag: # optional
            # Date for rollbackToDate
            #date: # optional
            # Reference URL for diff
            #referenceUrl: # optional
    
